# Generated by Django 4.0.2 on 2022-04-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('typeCo', models.CharField(max_length=100)),
                ('folio', models.CharField(max_length=100)),
                ('customerCode', models.CharField(max_length=100)),
                ('customers', models.CharField(max_length=100)),
                ('press', models.CharField(max_length=100)),
                ('request', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=100)),
                ('codeUyeda', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('development', models.CharField(max_length=100)),
                ('axis', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=100)),
                ('suaje', models.CharField(max_length=100)),
                ('substrate', models.CharField(max_length=100)),
                ('adhesive', models.CharField(max_length=100)),
                ('backup', models.CharField(max_length=100)),
                ('inkFront', models.CharField(max_length=100)),
                ('inkAdhesive', models.CharField(max_length=100)),
                ('inkBackup', models.CharField(max_length=100)),
                ('typeInk', models.CharField(max_length=100)),
                ('finished', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('delivery', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('letterColor', models.CharField(max_length=100)),
                ('typeDelivery', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=100)),
                ('prodpackaging', models.CharField(max_length=100)),
                ('annual', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('ink1', models.CharField(max_length=100)),
                ('ink2', models.CharField(max_length=100)),
                ('ink3', models.CharField(max_length=100)),
                ('ink4', models.CharField(max_length=100)),
                ('ink5', models.CharField(max_length=100)),
                ('ink6', models.CharField(max_length=100)),
                ('ink7', models.CharField(max_length=100)),
                ('ink8', models.CharField(max_length=100)),
                ('ink9', models.CharField(max_length=100)),
                ('ink10', models.CharField(max_length=100)),
                ('craete_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
            ],
        ),
    ]
