# Generated by Django 4.0.2 on 2022-05-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotizacion', 'verbose_name_plural': 'Cotizaciones'},
        ),
    ]
