# Generated by Django 4.0.2 on 2022-05-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_cotizacion_quote_cotizacion_quotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='annual',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='codeUyeda',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='customerCode',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='folio',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ink1',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ink10',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ink2',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ink3',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ink4',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ink5',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ink6',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ink7',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ink8',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='ink9',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='inkAdhesive',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='inkBackup',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='inkFront',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='quotation',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='speed',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
