# Generated by Django 4.0.2 on 2022-06-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_cotizacion_annual_alter_cotizacion_codeuyeda_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={},
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='folio',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
