# Generated by Django 4.0.2 on 2022-06-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_cotizacion_options_alter_cotizacion_folio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='quotation',
            new_name='cotizacion',
        ),
    ]
