# Generated by Django 4.0.2 on 2022-06-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_quotation_cotizacion_cotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='cotizacion',
            new_name='coti',
        ),
    ]
